on:
  push:
    branches:
      - main
      - develop
  pull_request: {}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn patch-package
      - run: yarn lint
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14", "16", "18"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn patch-package
      - run: yarn test
  passed:
    name: All CI passed
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    if: always()
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          RESULT_JSON: ${{ toJSON(needs) }}
        with:
          script: |
            const result = JSON.parse(process.env.RESULT_JSON);
            const passed = Object.values(result).every(({ result }) => result === 'success');
            if (!passed) process.exit(1);
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: release
      cancel-in-progress: false
    needs:
      - passed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ssh-key: ${{ secrets.DEPLOY_GIT_SSH_PRIVATE_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn patch-package
      - run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
