on:
  push:
    branches:
      - main
      - develop
  pull_request: {}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn patch-package
      - run: yarn lint
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14", "16", "18"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn patch-package
      - run: yarn test
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: release
      cancel-in-progress: false
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          ssh-key: ${{ secrets.DEPLOY_GIT_SSH_PRIVATE_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn patch-package
      - run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
